name: Build React Native App

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and archive iOS App
    runs-on: macos-15 # Found in VideoEdit/ios/VideoEdit.xcodeproj/project.pbxproj (IPHONEOS_DEPLOYMENT_TARGET = 15.1;)
    timeout-minutes: 10

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18 # Mentioned in package.json under engines section

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install --force

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          gem install cocoapods 
          pod install
          cd ..
