name: android workflow 
on:
  push:
    branches: 
    - main
jobs:
  android-build:
    name: checkout the code, and build the application
    runs-on: ubuntu-latest

    steps:
      - name: checkout repositary 
        uses: actions/checkout@v4
        
      # setting up the node js environment with 18 version mentioned in package.json 
      - name: setup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: installing nodejs dependencies
        run: npm install
        
      #setting up java version 17 based on gradle version mentioned in (gradle-wrapper.properties) 
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: checking the java version
        run: java -version
          
      # using lint mentioned in package.json("lint": "eslint .")
      - name: run lint stage 
        run: npm run lint 
        continue-on-error: true 

      # using test mentioned in package.json("test":"jest")
      - name: testing stage 
        run: npm test
        continue-on-error: true

        
        
