name: android workflow 
on:
  push:
    branches: 
    - main
env:
  JAVA_VERSION: '17'
  NODE_VERSION: '18'
  
jobs:
  android-build:
    name: checkout the code, and build the application
    runs-on: ubuntu-latest

    steps:
      - name: checkout repositary 
        uses: actions/checkout@v4
        
      # setting up the node js environment with 18 version mentioned in package.json 
      - name: setup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: installing nodejs dependencies
        run: npm install
        
      #setting up java version 17 based on gradle version mentioned in (gradle-wrapper.properties) 
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{env.JAVA_VERSION}}

      - name: giving execute persissions 
        run: chmod +x ./android/gradlew

      - name: checking lint errors
        run: npm run lint
        continue-on-error: true

      # this will covert the base 64 encoded to normal file 
      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/my-upload-key.keystore

      - name: setting up signing environment variables
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Build signed AAB
        run: |
          cd android
          ./gradlew assembleRelease

      - name: verify apk signature 
        run: |
          $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify --verbose android/app/build/outputs/apk/release/app-release.apk
          
      # added this stage because i am using github hosted runners so by default after running the pipeline runner will not be accesible so we need our build right so to get that we are adding this stage 
      - name: upload apk artifact
        uses: actions/upload-artifact@v4
        with: 
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
        


        
        
