name: android workflow 
on:
  push:
    branches: 
    - main
jobs:
  android-build:
    name: checkout the code, and build the application
    runs-on: ubuntu-latest

    steps:
      - name: checkout repositary 
        uses: actions/checkout@v4
        
      # setting up the node js environment with 18 version mentioned in package.json 
      - name: setup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: installing nodejs dependencies
        run: npm install
        
      # using lint mentioned in package.json("lint": "eslint .")
      - name: run lint stage 
        run: npm run lint

      # using test mentioned in package.json("test":"jest")
      - name: testing stage 
        run: npm test
        
