name: Build React Native App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    name: Build and archive iOS App
    runs-on: macos-15 # Found in VideoEdit/ios/VideoEdit.xcodeproj/project.pbxproj (IPHONEOS_DEPLOYMENT_TARGET = 15.1;)
    timeout-minutes: 10

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18 # Mentioned in package.json under engines section

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install --force

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          gem install cocoapods 
          pod install
          cd ..

      # Build the .xcarchive
      - name: List available schemes
        run: |
          cd ios
          xcodebuild -workspace VideoEdit.xcworkspace -list

      - name: Verify shared schemes
        run: |
          cd ios
          ls VideoEdit.xcodeproj/xcshareddata/xcschemes

      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: finding out xcode version
        run: |
          cat ios/podfile.lock | grep -i xcode
          cat ios/VideoEdit.xcodeproj/project.pbxproj | grep -i xcode
          cat ios/Gemfile | grep -i xcode
